### ISSUE TITLE
Broken links to API documentation and demo features

### ISSUE THREAD

**Issue by thiberaw** [ckeditor/ckeditor5-word-count#11]
links to 
[@ckeditor/ckeditor5-word-count package](https://ckeditor.com/docs/ckeditor5/latest/api/word-count.html)
[Word count demo](https://ckeditor.com/docs/ckeditor5/latest/features/word-count.html)
are broken.

![image](https://user-images.githubusercontent.com/5416065/60671320-5e71a300-9e62-11e9-9b92-8778ef86f9d6.png)

There's no documentation or demo page for this package.

**Comment by Reinmar** [comment]
Hi! Sorry for that. We've tagged the packages today and haven't yet published the docs.

**Comment by Reinmar** [comment]
The docs should be online in 1-2h.

**Comment by thiberaw** [comment]
@Reinmar sorry but the [link](https://ckeditor.com/docs/ckeditor5/latest/api/word-count.html) is still broken

**Comment by Reinmar** [comment]
Oh, thanks. I was checking the feature guide only.

**Comment by Reinmar** [comment]
@msamsel, we need to create `docs/api/wordcount.md` (similar to other packages like https://ckeditor.com/docs/ckeditor5/latest/api/mention.html).

Also, the actual link https://ckeditor.com/docs/ckeditor5/latest/api/word-count.html is incorrect because it contains `word-count.html` while it should be `wordcount.html` so please fix that too.

**Comment by Reinmar** [comment]
> Also, the actual link https://ckeditor.com/docs/ckeditor5/latest/api/word-count.html is incorrect because it contains `word-count.html` while it should be `wordcount.html` so please fix that too.

Doh, ignore the above. This package is actually called `word-count` so the link `api/word-count.html` is correct. The doc should be named `docs.api/word-count.md` as well. **BUT** this is incorrect:

![image](https://user-images.githubusercontent.com/156149/60745014-c9150280-9f78-11e9-83ce-ed8829a7b163.png)

All the classes are documented under the wrong namespace.
