### ISSUE TITLE
The WordCount#update event isn't fired on data load

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-word-count#18]
Which means that you have to calculate the initial stats yourself just like here:

https://github.com/ckeditor/ckeditor5-word-count/blob/e1a7a7e89de645dddda39127f23a25be7e196a3e/docs/_snippets/features/word-count-update.html#L30

**Comment by msamsel** [comment]
Event is fired, because `change:data` is fired after editors initialization. This trigger `update` event in word-count plugin: https://github.com/ckeditor/ckeditor5-word-count/blob/e1a7a7e89de645dddda39127f23a25be7e196a3e/src/wordcount.js#L122

I added a dedicated unit test checking this behaviour in related PR.

**Comment by Reinmar** [comment]
This case shows why unit tests are not the best solution to verify whether something works.

You're completely right that the event is fired. The problem is that... you can't listen to it. The below code will not work for initial data load: https://github.com/ckeditor/ckeditor5-word-count/blob/e1a7a7e89de645dddda39127f23a25be7e196a3e/docs/_snippets/features/word-count-update.js#L33-L45. If it was, you wouldn't need to hardcode the values in the HTML template.

When [designing this feature](https://github.com/ckeditor/ckeditor5-word-count/issues/1) we talked about `config.onUpdate` and, even though the proposed `WordCount#update` is fine, the priority was on `config.onUpdate`.

So, the thing to do to close this ticket is changing the snippet so it uses the config option and removing the hardcoded values. Also, we should have a test that `config.onUpdate` is triggered for the initial data load.

**Comment by Reinmar** [comment]
OK, I can see that the PR actually went in this direction. I was confused by its title and your comment here.

**Comment by mlewand** [comment]
Changing to docs issue.
