### ISSUE TITLE
Max character limit in editor

### ISSUE THREAD

**Issue by rathiayush** [ckeditor/ckeditor5-word-count#21]
Is there any feature in ckeditor5 which restricts user's input after certain character limit?

**Comment by Mgsy** [comment]
Hi, currently we don't have such a feature. We have opened a feature request for it - https://github.com/ckeditor/ckeditor5-word-count/issues/7. So, if this feature is important to you, add 👍 under the first post, so we'll be able to track the popularity of this request.
