### ISSUE TITLE
[Docs] Refine the feature guide and config docs

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-word-count#3]
After #2 is closed.

**Comment by Reinmar** [comment]
Notes from #2 review:

* Some configuration options are not mentioned.
* Code samples contain incomplete source code.
* Demos are non-realistic. They don't integrate the stats with the editor's UI either.
* Mentioned method and prop names are not correctly formatted (e.g. `method foo` -> `method the foo() method`.

**Comment by Reinmar** [comment]
Also, it should be clarified that there are 3 ways to integrate it – pass a container, get the container, listen to the event.

**Comment by Reinmar** [comment]
And we should use some more positive content for those editors.

**Comment by mlewand** [comment]
Since PR has been merged to `stable` 12 days ago but not to `master` and we had some more changes in the `master` branch. It is now causing conflicts and we can't merge it without resolving the conflicts.

(note for me as I was surprised seeing that PR is closed but the task remains open)

**Comment by oleq** [comment]
I merged stable into master (including changes from https://github.com/ckeditor/ckeditor5-word-count/pull/19) in aae2c2e.
