### ISSUE TITLE
The enter should not be counted as a character

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5-word-count#5]
Right now the newline is used to denote blocks and inline elements.

As @msamsel noticed it shouldn't count as a character:

![Peek 2019-06-28 15-51](https://user-images.githubusercontent.com/247363/60346969-a43eef00-99bc-11e9-9c0a-1717d54f4de6.gif)

**Comment by msamsel** [comment]
I think we should define some rules how words and characters are calculated. It should be also considered how word-count integrates with other plugins, like placeholder, tables, images, media embed etc.
Right now there is pretty basic solution, which might be improved in several ways.

**Comment by Reinmar** [comment]
Related issues:

* Media embed is treated as a character.
* An empty table 3x3 is treated ad 9 characters.

**Comment by Reinmar** [comment]
> I think we should define some rules how words and characters are calculated

I think it's best to check how it works in other editors (Word, GDocs). And see if there's some standard.
