### ISSUE TITLE
Add API to retrieve the content stats

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-word-count#6]
Currently, you can only listen to the `#update`. It'd also be cool if you could just retrieve the same information on demand.

Use case – you want to access that information on form submit to validate those values.

**Comment by jodator** [comment]
@Reinmar there are already two observable properties for `WordCount` plugin so you can:

```js
const wordCount = editor.plugins.get( 'WordCount' );

console.log( wordCount.words, wordCount.characters );
```

**Comment by Reinmar** [comment]
Nice! I've just stumbled upon them (cause they are not mentioned in the docs ;)).

However, there's a problem with them – they can be outdated. They should be implemented as getters which calculate the character count if the model changed since the last retrieval.

**Comment by Reinmar** [comment]
And once we fix the above, let's document them in the feature guide.

**Comment by scofalik** [comment]
Do they need to be getters if you would update after every change?

**Comment by Reinmar** [comment]
They are now calculated in a throttled event. So, not after every change.

**Comment by jodator** [comment]
> However, there's a problem with them – they can be outdated. They should be implemented as getters which calculate the character count if the model changed since the last retrieval.

Quick idea: cache them. As we already calculate them in a throttled event we could have these values either taken directly or calculate them if the throttled event is not finished.

So the idea is that a `change` event listener would set some internal flag, ie `this._freshData` to `false` and the throttled method would set `this._freshData` to `true` once resolved. This way the getters could either take the `words` and `characters` directly or calculate them if needed.

But OTOH - this might be not needed as the getters are rather less frequent use and the calculate method is fast enough.

**Comment by Reinmar** [comment]
> But OTOH - this might be not needed as the getters are rather less frequent use and the calculate method is fast enough.

Good point. It doesn't seem necessary to cache them. If anyone wants to access them frequently, then they should use the event.

**Comment by mlewand** [comment]
Definitely getters will be needed, otherwise we have a risk of edge case when validation based on our word count will pass content longer than expected.

**Comment by oleq** [comment]
FYI: I smuggled a new `#update` event demo in the PR

![Kapture 2019-08-02 at 13 49 02](https://user-images.githubusercontent.com/1099479/62368246-59207a80-b52c-11e9-9182-a0830d61fb2f.gif)

**Comment by jodator** [comment]
> FYI: I smuggled a new `#update` event demo in the PR

:thinking: `-2` might be confusing there :D but I don't have better idea ;)
